// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmhRcjM83WBIsHJ1JB2d6TY8lcsBIiD1A',
    appId: '1:831217477879:web:f2d8b715a27cd7a688cbf2',
    messagingSenderId: '831217477879',
    projectId: 'machinetrack-701bd',
    authDomain: 'machinetrack-701bd.firebaseapp.com',
    storageBucket: 'machinetrack-701bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLtpMjLj4ygx9SeHcmxTaoa8lVo-ogYVk',
    appId: '1:831217477879:android:d3d94074ca134a0488cbf2',
    messagingSenderId: '831217477879',
    projectId: 'machinetrack-701bd',
    storageBucket: 'machinetrack-701bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKWjpWEex4fAp55e1C4lMdxekpygVqVko',
    appId: '1:831217477879:ios:900f572e6d1198bd88cbf2',
    messagingSenderId: '831217477879',
    projectId: 'machinetrack-701bd',
    storageBucket: 'machinetrack-701bd.firebasestorage.app',
    iosBundleId: 'com.machinetrack.frontend',
  );
}
